server:
  port: 8013

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/queue
    username: example
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop

  output:
    ansi:
      enabled: ALWAYS